Tweak WKT generation and tests.
developmentseed/geojson-pydantic pull request #140
Opened 2023-07-17 17:35 UTC by eseglem

## What I am changing

- Attempt to fix issues with WKT and its tests.

## How I did it

- Adjusted `MultiPoint` to include parentheses around each set of Point coordinates.
- Adjusted tests because we can no longer rely on a consistent output from Shapely / Geos.

## How you can test it

- Attempted to address all the cases in a new test.

## Related Issues

- Fixes #139 Though some of the fix is just avoiding the issues in Shapely / Geos not changing anything for us. 

The `NaN` behavior in Geos is weird, as it is not valid WKT, but I understand what they are doing rather than assuming `0.0` as the Z value. It doesn't look entirely resolved on the Shapely side either, so I don't think there is much to do for now. Unless we just stop using the `force_z` stuff, and let stuff like `"MULTIPOINT Z ((0.0 0.0), (1.0 1.0 1.0))"` be output. It is parseable by `shapely.from_wkt` at least. So maybe that is not so bad? I think the reason for how it was was because their output added the 0, so we did too.

2023-07-17 17:36 UTC, eseglem commented on geojson_pydantic/geometries.py
> +GeometryCollection.model_rebuild()
Was getting a deprecated warning from `update_forward_refs` so I updated it.

2023-07-17 21:31 UTC, vincentsarago commented on geojson_pydantic/geometries.py
> +        # return _position_list_wkt_coordinates(coordinates, force_z)
can we remove the comment here?

2023-07-17 21:32 UTC, vincentsarago commented on tests/test_geometries.py
> +@pytest.mark.parametrize(
😍

2023-07-20 00:04 UTC, vincentsarago requested changes
thanks @eseglem 

just remove the comment and update the changelog and we can 🚀

2023-07-20 00:22 UTC, vincentsarago approved these changes

2023-07-20 00:22 UTC, merged